ninenty_nine_cats/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only:[:index, :show, :create, :new, :edit]
end

ninenty_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninenty_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string
#  name        :string           not null
#  sex         :string(1)
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
require 'date'
class Cat < ApplicationRecord
    COLORS = %w(white black red yellow)

    validates :birth_date, :name, :description, presence: true
    validates :color, inclusion: {in: Cat::COLORS, message: 'Choose color'}
    validates :sex, inclusion: {in: %w(M F), message: 'Choose M or F'}

    has_many :rentals,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

    def age
        (Date.today - self.birth_date).to_i/365.25
    end




end

ninenty_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint           not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING")
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class CatRentalRequest < ApplicationRecord
    STATUS = %w(PENDING APPROVED DENIED)
    validates :cat_id, :start_date, :end_date, :status, presence: true
    validates :status, inclusion: {in: CatRentalRequest::STATUS}

    belongs_to :cat,
        foreign_key: :cat_id,
        class_name: :Cat




end

ninenty_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninenty_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find(params[:id])
    render :show

  end

  def create
    @cat = Cat.new(cat_params)

    if @cat.save
      redirect_to cat_url(@cat)
    else
      render :new
    end


  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    @cat = Cat.find(params[:id])
    render :edit
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  def cat_params
    params.require(:cat).permit(:name, :birth_date, :color, :sex, :description)
  end

end

ninenty_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninenty_nine_cats/app/helpers/cat_helper.rb
module CatHelper
end

ninenty_nine_cats/app/helpers/cats_helper.rb
module CatsHelper
end

ninenty_nine_cats/app/views/cats/_cat.html.erb
<ul> 
    <li><%= catt.name %></li>
    <li><%= catt.birth_date %></li>
    <li><%= catt.color %></li>
    <li><%= catt.sex %></li>
    <li><%= catt.description %></li>

    <% if action == :show %>
        <li><a href="<%= cats_url %>">Cat Index</a></li>
    <% else %>
        <li><a href="<%= cat_url(catt) %>">Cat's Show Page</a></li>
    <% end %>
</ul>

ninenty_nine_cats/app/views/cats/_form.html.erb
<%url = catt.persisted? ? edit_cat_url(catt) : cats_url %>
<form action="<%= url%>" method="POST">
   <%= sanitize "<input type=\"hidden\" name=\"_method\" value=\"PATCH\">" if catt.persisted?%>
    <label> Name:
         <input type="text" name="cat[name]" value='<%=catt.name%>'> 
    </label>
    <br><br>
    <label> Select Sex:
    <br>
    <input id="male" type="radio" name="cat[sex]" value="M" <%= :checked if catt.sex == "M" %>> 
    <label for="male"> Male <label>
    
    <input id="female" type="radio" name="cat[sex]" value="F" <%= :checked if catt.sex == "F" %>> 
    <label for="female"> Female <label>
    </label>
    <br><br>

    <label for="catcolor">Select Color</label>
    <select id="catcolor" name="cat[color]">
        <option selected disabled>--Choose Color--</option>
        <% Cat::COLORS.each do |color| %>
        <option value="<%=color%>"  <%= :selected if catt.color == color%>><%=color.capitalize%></option>
        <%end %>
    </select>
    <br><br>
    
    <label for="birthdate">Select Birth-Date</label>
    <input id="birthdate" name="cat[birth_date]" type="date" value='<%=catt.birth_date%>'>
    <br><br>

    <label for="description">Description of Cat</label>
    <textarea id="description" name="cat[description]" rows="5" cols="50"> 
    <%=catt.description%></textarea>
    <br>
    <br>
    <br>
    <input type="submit" value="Submit">
    <p> Click the "Submit" button and the cat will be added to our database</p>

</form>

ninenty_nine_cats/app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

ninenty_nine_cats/app/views/cats/edit.html.erb
<h1>Edit Cat</h1>
<%= render 'form', catt: @cat%>

ninenty_nine_cats/app/views/cats/index.html.erb
<h1>Here are all of our Cats!</h1>
<ul>
    <% @cats.each do |catt| %>
        <%= render 'cat', catt: catt, action: :index  %>
        
    <%end %>
</ul>

ninenty_nine_cats/app/views/cats/new.html.erb
<h1>New Cat</h1>
<%= render 'form', catt: @cat%>

ninenty_nine_cats/app/views/cats/old_edit.html.erb
<h1>Edit Cat</h1>
<form action="<%= edit_cat_url(@cat)%>" method="POST">
    <input type="hidden" name="_method" value="PATCH">
    <label> Name:
         <input type="text" name="cat[name]" value='<%=@cat.name%>'> 
    </label>
    <br><br>
    <label> Select Sex:
    <br>
    <input id="male" type="radio" name="cat[sex]" value="M" <%= :checked if @cat.sex == "M" %>> 
    <label for="male"> Male <label>
    
    <input id="female" type="radio" name="cat[sex]" value="F" <%= :checked if @cat.sex == "F" %>> 
    <label for="female"> Female <label>
    </label>
    <br><br>

    <label for="catcolor">Select Color</label>
    <select id="catcolor" name="cat[color]">
        <option selected disabled>--Choose Color--</option>
        <% Cat::COLORS.each do |color| %>
        <option value="<%=color%>"  <%= :selected if @cat.color == color%>><%=color.capitalize%></option>
        <%end %>
    </select>
    <br><br>
    
    <label for="birthdate">Select Birth-Date</label>
    <input id="birthdate" name="cat[birth_date]" type="date" value='<%=@cat.birth_date%>'>
    <br><br>

    <label for="description">Description of Cat</label>
    <textarea id="description" name="cat[description]" rows="5" cols="50"> 
    <%=@cat.description%></textarea>
    <br>
    <br>
    <br>
    <input type="submit" value="Submit">
    <p> Click the "Submit" button and the cat will be added to our database</p>

</form>

ninenty_nine_cats/app/views/cats/show.html.erb
<h1><%= @cat.name %> Show Page</h1>

<table>
    <thead>
        <tr> 
            <th colspan="2"><%= @cat.name %></th>
        </tr>
    </thead>
    <tbody> 
        <tr> 
            <td>Attribute</td>
            <td>Value</td>
        </tr>
        <tr> 
            <td>Age</td>
            <td>About <%= @cat.age %> years</td>
        </tr>
        <tr> 
            <td>Birth Date</td>
            <td><%= @cat.birth_date %></td>
        </tr>
        <tr> 
            <td>Color</td>
            <td><%= @cat.color %></td>
        </tr>
        <tr> 
            <td>Sex</td>
            <td><%= @cat.sex%></td>
        </tr>
    </tbody>
</table>

<table>
    <thead>
        <tr> 
            <th colspan="4">Rental Requests</th>
        </tr>
    </thead>
    <tbody> 
        <tr> 
            <td>User</td>
            <td>Start Date</td>
            <td>End Date</td>
            <td>Status</td>
        </tr>
        <tr> 
            <td>FILLER</td>
            <td>FILLER</td>
            <td>FILLER</td>
            <td>FILLER</td>
        </tr>
    </tbody>
</table>

ninenty_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinentyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>